name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: rutvk00/paytm-main:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull rutvk00/paytm-main:latest  # Replace with your Docker Hub username and repository
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Pull the latest images
          sudo docker pull rutvk00/paytm-main:latest
          sudo docker pull postgres:latest  # Use an appropriate PostgreSQL version

          # Stop and remove existing containers if any
          sudo docker stop paytm-main || true
          sudo docker rm paytm-main || true
          sudo docker stop paytm-postgres || true
          sudo docker rm paytm-postgres || true

          # Run PostgreSQL container
          sudo docker run -d --name paytm-postgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=postgres -p 5431:5432 postgres:latest


          # Run your application container linked to PostgreSQL
          sudo docker run -d --name paytm-main --link paytm-postgres:postgres -p 3005:3000 --restart always -e DATABASE_URL=postgresql://postgres:mysecretpassword@paytm-postgres:5432/postgres rutvk00/paytm-main:latest


